site_name: Raapoi Cluster Documentation
nav: 
  - Documentation: index.md
  - Support: support.md
  - Utilisation: ganglia.md

theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True
      baselevel: 2
      toc_depth: 2

extra_css: [extra.css]

site_url: https://matty-plumski.github.io/vuwrc/